on:
  workflow_dispatch:
  push:
    branches: main
    
name: 02-publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: print-message
        run: echo "Publish!"
